services:
  # Web Service
  - type: web
    name: etudesync
    env: node
    region: oregon
    plan: free
    buildCommand: echo "No build required"
    startCommand: npm start
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: etudesync-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: etudesync-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: etudesync-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: etudesync-db
          property: password

databases:
  # MySQL Database
  - name: etudesync-db
    databaseName: etudesync
    plan: free
